### PR TITLE
New JSON feature (minimal) with recommendations by @jakopako

### PR DESCRIPTION
**Pull request by MarkJaroski**
I've tested this code for regressions, but the real venue site I was testing the new feature with is down with a 505, so my next step will be to add a unit test for this.

### CODE REVIEW

**Comment by jakopako** [comment]
Awesome, thanks!

What's the reason that you added an 'install dependencies' step to the go-tests.yml? The dependencies should be install automatically in the 'Test' step.

**Comment by MarkJaroski** [comment]
> Awesome, thanks!
> 
> What's the reason that you added an 'install dependencies' step to the go-tests.yml file? The dependencies should be installed automatically in the 'Test' step.

For some reasons the tests failed in my branch until I did that. It could be that the dependency files weren't yet correct.

**Comment by jakopako** [comment]
> > Awesome, thanks!
> > What's the reason that you added an 'install dependencies' step to the go-tests.yml file? The dependencies should be installed automatically in the 'Test' step.
> 
> For some reasons the tests failed in my branch until I did that. It could be that the dependency files weren't yet correct.

hmmm ok. Yeah might be that the the dependency files weren't correct. I'll try without this extra step in the go-tests.yml file and if it fails, I'll re-add it.

**Comment by jakopako** [comment]
seems to work :)

**Pull request merged**
